// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/ngu/controller.js', ['ngu.Controller'], [], false);
goog.addDependency('../../../../src/ngu/directive.js', ['ngu.Directive'], [], false);
goog.addDependency('../../../../src/ngu/ngu.js', ['ngu'], ['ngu.Controller', 'ngu.Directive', 'ngu.Service'], false);
goog.addDependency('../../../../src/ngu/service.js', ['ngu.Service'], [], false);
