// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/ngu/configuration.js', ['ngu.Configuration'], [], false);
goog.addDependency('../../../../src/ngu/controller.js', ['ngu.Controller'], [], false);
goog.addDependency('../../../../src/ngu/d/fade.js', ['ngu.d.Fade'], ['ngu.Directive'], false);
goog.addDependency('../../../../src/ngu/d/include-replace.js', ['ngu.d.IncludeReplace'], ['ngu.Directive'], false);
goog.addDependency('../../../../src/ngu/d/show-after-transition.js', ['ngu.d.ShowAfterTransition'], ['ngu.Directive'], false);
goog.addDependency('../../../../src/ngu/d/transition-end.js', ['ngu.d.TransitionEnd'], ['ngu.Directive'], false);
goog.addDependency('../../../../src/ngu/directive.js', ['ngu.Directive'], [], false);
goog.addDependency('../../../../src/ngu/ngu.js', ['ngu'], ['ngu.Configuration', 'ngu.Controller', 'ngu.Directive', 'ngu.Provider', 'ngu.Service', 'ngu.d.Fade', 'ngu.d.IncludeReplace', 'ngu.d.ShowAfterTransition', 'ngu.d.TransitionEnd'], false);
goog.addDependency('../../../../src/ngu/provider.js', ['ngu.Provider', 'ngu.ProviderService'], ['ngu.Service'], false);
goog.addDependency('../../../../src/ngu/service.js', ['ngu.Service'], [], false);
